# Generated by Django 5.1 on 2024-08-18 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_electricity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
