# Generated by Django 5.1 on 2024-08-18 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_electricity', '0002_alter_user_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
