# Generated by Django 5.1 on 2024-08-18 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_electricity', '0003_alter_user_mobile_number_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/'),
        ),
    ]
