# Generated by Django 5.1 on 2024-08-29 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_electricity', '0007_user_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Electricity_rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(blank=True, max_length=20, null=True)),
                ('rate', models.IntegerField()),
            ],
        ),
    ]
