# Generated by Django 5.1 on 2024-08-29 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_electricity', '0008_electricity_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electricity_rate',
            name='month',
        ),
        migrations.AddField(
            model_name='electricity_rate',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='electricity_rate',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
