# Generated by Django 5.1 on 2024-09-02 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_electricity', '0009_remove_electricity_rate_month_electricity_rate_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_order', models.CharField(blank=True, max_length=60, null=True)),
                ('amount', models.IntegerField()),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('On the way', 'On the way'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Returned', 'Returned')], max_length=60, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_electricity.user')),
            ],
        ),
    ]
