# Generated by Django 5.1 on 2024-09-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_electricity', '0011_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Electricity_news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.TextField()),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
